target . delete ( "teacher1" ) 
local pc_job = pc . get_job ( ) 
if pc_job ~= 0 then 
say_title ( "Yanlýþ Eðitim " ) 
say ( "" ) 
say ( "Özür dilerim." ) 
say ( "Sadece Savaþçýlar Bedensel Savaþý seçebilir." ) 
say ( "" ) 
say ( "" ) 
if pc_job == 0 then 
say_reward ( "Bir Savaþçý,  Zihinsel Savaþý " ) 
say_reward ( "veya Bedensel Savaþý " ) 
say_reward ( "seçebilir." ) 
elseif pc_job == 1 then 
say_reward ( "Bir Ninja, Yakin Dövüþ veya" ) 
say_reward ( "Uzak Dövüþ eðitimini" ) 
say_reward ( "seçebilir." ) 
elseif pc_job == 2 then 
say_reward ( "Bir Sura, Büyülü Silah" ) 
say_reward ( "veya Kara Büyü eðitimini" ) 
say_reward ( "seçebilir." ) 
elseif pc_job == 3 then 
say_reward ( "Bir Þaman, Ejderha Gücü eðitimini" ) 
say_reward ( "veya Ýyileþtirme eðitimini" ) 
say_reward ( "seçebilir." ) 
end 
say ( "" ) 
return 
end 
say_title ( "Bedensel Savaþ eðitimi" ) 
say ( "Bedensel savaþ eðitimi hýzlý savaþma eðitimi ve" ) 
say ( "metodlarýný, ayrýca geliþmiþ temel saldýrý " ) 
say ( "tiplerini içerir." ) 
say_reward ( "Gereksinim: Seviye 5 ve üstü bir savaþçý olmak" ) 
say ( "" ) 
local s = select ( "Baþla" , "Daha sonra" ) 
if 2 == s then 
return 
end 
if pc . get_job ( ) ~= 0 or pc . get_skill_group ( ) ~= 0 then 
test_chat ( "npc_is_same_job:" .. bool_to_str ( npc_is_same_job ( ) ) ) 
test_chat ( "pc.get_skill_group:" .. pc . get_skill_group ( ) ) 
test_chat ( "pc_job:" .. pc . get_job ( ) ) 
return 
end 
set_state ( "start" ) 
pc . set_skill_group ( 1 ) 
pc . clear_skill ( ) 
char_log ( 0 , "CLEAR_SKILL" , "Ögretmen silindikten sonraki dogal yetenek." ) 
say_title ( "Bedensel savaþ eðitimini seçtin." ) 
say ( "Hoþgeldin!" ) 
if not pc . is_clear_skill_group ( ) then 
say ( "Ders almayý seçtiðin için becerilerini " ) 
say ( "normal olarak veriyorum" ) 
say ( "Geliþtirmek için beceri kitabýna ihtiyacin olacak." ) 
say_title ( "Bilgi:" ) 
say_reward ( "Becerilerin normal Olarak Verildi." ) 
say ( "" ) 
pc . set_skill_level ( 124 , 59 ) 
pc . set_skill_level ( 130 , 59 ) 
pc . set_skill_level ( 131 , 59 ) 
pc . set_skill_level ( 121 , 59 ) 
pc . set_skill_level ( 129 , 59 ) 
pc . set_skill_level ( 126 , 59 ) 
pc . set_skill_level ( 127 , 59 ) 
pc . set_skill_level ( 128 , 59 ) 
pc . set_skill_level ( 137 , 59 ) 
pc . set_skill_level ( 138 , 59 ) 
pc . set_skill_level ( 139 , 59 ) 
pc . set_skill_level ( 122 , 2 ) 
else 
say_reward ( "Yeni bir ders seçtiginde," ) 
say_reward ( "daha fazla tecrübe puani almayacaksin." ) 
say ( "" ) 
end 
clear_letter ( ) 
